### ISSUE TITLE
Typo in Abl-Imatinib yaml file? 

### ISSUE THREAD

**Issue by steven-albanese** [choderalab/yank-examples#56]
Looks like there is a typo in `ph_tolerance` for epik in the abl-imatinib yaml file: 
```
epik:
      select: 0
      ph: 7.4
      ph_tolerance: 7.0
```

I think `ph_tolerance` is set to 0.7 on getyank.org.
